site_name: SwitchTemplate
docs_dir: core/components/switchtemplate/docs/mkdocs
site_dir: _build/site

repo_url: https://github.com/Jako/SwitchTemplate

pages:
- Home: 'index.md'
- Installation: 'installation.md'
- Usage: 'usage.md'

theme: flatly

markdown_extensions:
    - footnotes
    - tables
